import "./globals.css";
import { Inter } from "next/font/google";
import Link from "next/link";
import React, { PropsWithChildren } from "react";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const Layout: React.FC<PropsWithChildren> = ({ children }) => {
  return (
    <div className="h-screen flex overflow-hidden">
      <div className="md:flex md:flex-shrink-0">
        <div className="flex flex-col w-full md:w-64">
          <div className="h-0 flex-1 flex flex-col overflow-y-auto">
            <nav className="mt-5 px-2 space-y-1">
              <Link
                className="text-gray-600 hover:bg-gray-50 hover:text-gray-900 group flex items-center px-2 py-2 text-base font-medium rounded-md"
                href="/"
              >
                Home
              </Link>
              <Link
                className="text-gray-600 hover:bg-gray-50 hover:text-gray-900 group flex items-center px-2 py-2 text-base font-medium rounded-md"
                href="/product-list/1"
              >
                Products
              </Link>
            </nav>
          </div>
        </div>
      </div>
      <div className="md:flex flex-1 overflow-hidden">
        <main className="flex-1 relative overflow-y-auto">
          <div className="py-6 px-4 sm:px-6 lg:px-8">{children}</div>
        </main>
      </div>
    </div>
  );
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Layout>{children}</Layout>
      </body>
    </html>
  );
}
